Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/nbclient/client.py", line 1107, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/nbclient/client.py", line 852, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pyqec.sparse import BinaryMatrix, BinaryVector
from pyqec.classical import LinearCode, BinarySymmetricChannel
from pyqec.experiments import ClassicalDecodingExperiment, Laboratory
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-1-4e6ceed659ac>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0mpyqec[0m[0;34m.[0m[0msparse[0m [0;32mimport[0m [0mBinaryMatrix[0m[0;34m,[0m [0mBinaryVector[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mfrom[0m [0mpyqec[0m[0;34m.[0m[0mclassical[0m [0;32mimport[0m [0mLinearCode[0m[0;34m,[0m [0mBinarySymmetricChannel[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mfrom[0m [0mpyqec[0m[0;34m.[0m[0mexperiments[0m [0;32mimport[0m [0mClassicalDecodingExperiment[0m[0;34m,[0m [0mLaboratory[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/pyqec/__init__.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mclassical[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mexperiments[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0msparse[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/pyqec/classical.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0;34m.[0m[0mpyqec[0m [0;32mimport[0m [0mLinearCode[0m[0;34m,[0m [0mBinarySymmetricChannel[0m[0;34m,[0m [0mFlipDecoder[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mImportError[0m: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/pyqec/pyqec.cpython-39-x86_64-linux-gnu.so)
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/pyqec/pyqec.cpython-39-x86_64-linux-gnu.so)

